
function timeToInt(str) {
  let parts = str.split(':')
  return 60 * parseInt(parts[0]) + parseInt(parts[1])
}

function intToTime(num) {
  return Math.floor(num / 60) + ':' + ((num % 60) + '').padStart(2, '0')
}

var zelena = new Line('Zelena', [])
zelena.add(new Stop('Skandis'))
zelena.add(new Stop('Kepenys'))
zelena.add(new Stop('Inkstos'))
zelena.add(new Stop('Ausis'))
zelena.add(new Stop('Burda'))
zelena.add(new Stop('Dantys'))
zelena.add(new Stop('Kelias'))
zelena.add(new Stop('Alegia'))
zelena.add(new Stop('Nuotekog'))
zelena.add(new Stop('Motavimo'))
zelena.add(new Stop('Oerspote'))
zelena.add(new Stop('Dubenelis'))
zelena.add(new Stop('Dauskine'))
zelena.add(new Stop('Padeklas'))
zelena.add(new Stop('Virdulis'))
zelena.add(new Stop('Keptune'))
zelena.add(new Stop('Pudas'))
zelena.add(new Stop('Aparatas'))
zelena.add(new Stop('Orkaite'))
zelena.add(new Stop('Skaundintuas'))
zelena.add(new Stop('Smakras'))
zelena.add(new Stop('Trintuvas'))
zelena.setDistances([10, 7, 3, 8, 2, 12, 8, 3, 7, 5, 3, 8, 4, 7, 2, 6, 6, 9, 12, 3, 7])
zelena.addForward(timeToInt('8:00'))
zelena.addForward(timeToInt('10:10'))
zelena.addForward(timeToInt('12:05'))
zelena.addForward(timeToInt('14:20'))
zelena.addForward(timeToInt('15:30'))
zelena.addForward(timeToInt('16:00'))
zelena.addForward(timeToInt('17:10'))
zelena.addForward(timeToInt('18:00'))
zelena.addForward(timeToInt('20:00'))
zelena.addBackward(timeToInt('9:00'))
zelena.addBackward(timeToInt('11:00'))
zelena.addBackward(timeToInt('13:00'))
zelena.addBackward(timeToInt('14:05'))
zelena.addBackward(timeToInt('15:00'))
zelena.addBackward(timeToInt('16:50'))
zelena.addBackward(timeToInt('17:40'))
zelena.addBackward(timeToInt('18:30'))
zelena.addBackward(timeToInt('19:15'))
zelena.addBackward(timeToInt('21:00'))

var cerna = new Line('Cerna', [])
cerna.add(new Stop('Ausis'))
cerna.add(new Stop('Lekstude'))
cerna.add(new Stop('Raktai'))
cerna.add(new Stop('Pakuba'))
cerna.add(new Stop('Sakute'))
cerna.add(new Stop('Kilimos'))
cerna.add(new Stop('Peilis'))
cerna.add(new Stop('Raudon'))
cerna.add(new Stop('Pankolis'))
cerna.add(new Stop('Savila'))
cerna.add(new Stop('Kajenas'))
cerna.add(new Stop('Artero'))
cerna.setDistances([7, 5, 3, 8, 2, 9, 8, 7, 7, 3, 8])
cerna.addForward(timeToInt('9:15'))
cerna.addForward(timeToInt('10:45'))
cerna.addForward(timeToInt('12:10'))
cerna.addForward(timeToInt('14:20'))
cerna.addForward(timeToInt('15:30'))
cerna.addForward(timeToInt('17:05'))
cerna.addForward(timeToInt('18:25'))
cerna.addForward(timeToInt('19:30'))
cerna.addBackward(timeToInt('9:00'))
cerna.addBackward(timeToInt('11:11'))
cerna.addBackward(timeToInt('13:08'))
cerna.addBackward(timeToInt('14:15'))
cerna.addBackward(timeToInt('15:20'))
cerna.addBackward(timeToInt('17:40'))
cerna.addBackward(timeToInt('18:50'))
cerna.addBackward(timeToInt('21:30'))

var oranzova = new Line('Oranzova', [])
oranzova.add(new Stop('Veidas'))
oranzova.add(new Stop('Oad'))
oranzova.add(new Stop('Galva'))
oranzova.add(new Stop('Kakta'))
oranzova.add(new Stop('Raudon'))
oranzova.add(new Stop('Kurk'))
oranzova.add(new Stop('Gerle'))
oranzova.add(new Stop('Kaklos'))
oranzova.add(new Stop('Mais'))
oranzova.add(new Stop('Oda'))
oranzova.add(new Stop('Pyrhe'))
oranzova.add(new Stop('Debron'))
oranzova.add(new Stop('Vetero'))
oranzova.add(new Stop('Ilas'))
oranzova.setDistances([6, 12, 9, 12, 14, 8, 9, 5, 11, 14, 10, 3, 2])
oranzova.addForward(timeToInt('9:15'))
oranzova.addForward(timeToInt('10:45'))
oranzova.addForward(timeToInt('12:10'))
oranzova.addForward(timeToInt('14:20'))
oranzova.addForward(timeToInt('15:30'))
oranzova.addForward(timeToInt('17:05'))
oranzova.addForward(timeToInt('18:25'))
oranzova.addForward(timeToInt('19:30'))
oranzova.addBackward(timeToInt('9:00'))
oranzova.addBackward(timeToInt('11:11'))
oranzova.addBackward(timeToInt('13:08'))
oranzova.addBackward(timeToInt('15:20'))
oranzova.addBackward(timeToInt('17:40'))
oranzova.addBackward(timeToInt('21:30'))

var modra = new Line('Modra', [])
modra.add(new Stop('Kajenas'))
modra.add(new Stop('Madra'))
modra.add(new Stop('Kaklos'))
modra.add(new Stop('Maz'))
modra.add(new Stop('Imbie'))
modra.add(new Stop('Kriaukle'))
modra.add(new Stop('Plaueu'))
modra.add(new Stop('Vonia'))
modra.add(new Stop('Dušas'))
modra.add(new Stop('Monte'))
modra.add(new Stop('Arnion'))
modra.add(new Stop('Aparatas'))
modra.add(new Stop('Coelo'))
modra.add(new Stop('Morbag'))
modra.add(new Stop('Sipos'))
modra.setDistances([18, 7, 10, 12, 14, 4, 3, 8, 7, 11, 9, 4, 14, 6])
modra.addForward(timeToInt('9:00'))
modra.addForward(timeToInt('12:00'))
modra.addForward(timeToInt('15:00'))
modra.addForward(timeToInt('16:45'))
modra.addForward(timeToInt('18:10'))
modra.addForward(timeToInt('19:38'))
modra.addForward(timeToInt('20:02'))
modra.addForward(timeToInt('21:52'))
modra.addBackward(timeToInt('8:30'))
modra.addBackward(timeToInt('10:00'))
modra.addBackward(timeToInt('12:05'))
modra.addBackward(timeToInt('14:11'))
modra.addBackward(timeToInt('15:25'))
modra.addBackward(timeToInt('16:08'))
modra.addBackward(timeToInt('17:40'))
modra.addBackward(timeToInt('18:20'))
modra.addBackward(timeToInt('20:10'))
modra.addBackward(timeToInt('21:45'))

var bila = new Line('Bila', [])
bila.add(new Stop('Motavimo'))
bila.add(new Stop('Kamas'))
bila.add(new Stop('Eismas'))
bila.add(new Stop('Bazikos'))
bila.add(new Stop('Druska'))
bila.add(new Stop('Spintele'))
bila.add(new Stop('Stendas'))
bila.add(new Stop('Pagolle'))
bila.add(new Stop('Skalbimo'))
bila.add(new Stop('Notermo'))
bila.add(new Stop('Paladir'))
bila.setDistances([18, 12, 7, 8, 11, 4, 2, 9, 3, 1])
bila.addForward(timeToInt('9:00'))
bila.addForward(timeToInt('9:50'))
bila.addForward(timeToInt('10:45'))
bila.addForward(timeToInt('11:18'))
bila.addForward(timeToInt('12:00'))
bila.addForward(timeToInt('12:20'))
bila.addForward(timeToInt('15:05'))
bila.addForward(timeToInt('16:00'))
bila.addForward(timeToInt('17:30'))
bila.addForward(timeToInt('18:05'))
bila.addForward(timeToInt('20:15'))
bila.addForward(timeToInt('22:00'))
bila.addBackward(timeToInt('10:00'))
bila.addBackward(timeToInt('14:11'))
bila.addBackward(timeToInt('16:08'))
bila.addBackward(timeToInt('17:28'))
bila.addBackward(timeToInt('18:20'))
bila.addBackward(timeToInt('20:08'))
bila.addBackward(timeToInt('22:40'))

var lines = [zelena, cerna, oranzova, modra, bila]
